import { Link } from 'react-router-dom';
import { Zap, Github, Twitter } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="relative border-t border-white/[0.06] bg-[#050508] mt-24">
      <div className="max-container py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10">

          {/* Brand */}
          <div className="md:col-span-2">
            <Link to="/" className="inline-flex items-center gap-2.5 mb-4 cursor-pointer" aria-label="PredictaFC Home">
              <div className="w-8 h-8 rounded-lg bg-gold/10 border border-gold/30 flex items-center justify-center">
                <Zap className="w-4 h-4 text-gold" aria-hidden="true" />
              </div>
              <span className="font-heading text-base font-bold">
                <span className="text-white">Predicta</span><span className="gold-text">FC</span>
              </span>
            </Link>
            <p className="text-slate-500 text-sm leading-relaxed max-w-xs">
              AI-powered World Cup match predictions built on advanced machine learning models and historical football data.
            </p>
            <div className="flex gap-3 mt-5">
              <a href="#" aria-label="GitHub" className="w-9 h-9 rounded-lg border border-white/10 flex items-center justify-center text-slate-500 hover:text-white hover:border-white/20 transition-colors cursor-pointer">
                <Github className="w-4 h-4" aria-hidden="true" />
              </a>
              <a href="#" aria-label="Twitter" className="w-9 h-9 rounded-lg border border-white/10 flex items-center justify-center text-slate-500 hover:text-white hover:border-white/20 transition-colors cursor-pointer">
                <Twitter className="w-4 h-4" aria-hidden="true" />
              </a>
            </div>
          </div>

          {/* Links */}
          <div>
            <p className="text-xs font-heading font-semibold tracking-widest text-slate-600 uppercase mb-4">Platform</p>
            <ul className="space-y-2.5">
              {[['Groups','groups'],['Knockout','knockout'],['Teams','teams'],['Predict','predict']].map(([label, to]) => (
                <li key={to}>
                  <Link to={`/${to}`} className="text-sm text-slate-500 hover:text-white transition-colors cursor-pointer">{label}</Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <p className="text-xs font-heading font-semibold tracking-widest text-slate-600 uppercase mb-4">Info</p>
            <ul className="space-y-2.5">
              {[['Model','about'],['About','about'],['Methodology','about']].map(([label, to]) => (
                <li key={label}>
                  <Link to={`/${to}`} className="text-sm text-slate-500 hover:text-white transition-colors cursor-pointer">{label}</Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="border-t border-white/[0.06] mt-10 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-xs text-slate-600">© 2026 PredictaFC. All predictions are generated by AI models.</p>
          <p className="text-xs text-slate-700 font-heading">Powered by Machine Learning</p>
        </div>
      </div>
    </footer>
  );
}
